#!/bin/bash
# Quick Test Setup & Run Guide

echo "=== Frontend E2E Test Quick Start ==="
echo ""
echo "Prerequisites:"
echo "  ✓ Backend running: http://localhost:4000"
echo "  ✓ Frontend running: http://localhost:5173"
echo "  ✓ Test users seeded in database"
echo ""
echo "Step 1: Ensure backend is running"
echo "  cd backend && npm run dev"
echo ""
echo "Step 2: Ensure frontend is running"
echo "  cd frontend && npm run dev"
echo ""
echo "Step 3: Run E2E tests"
echo "  cd frontend && npm run test:e2e"
echo ""
echo "Options:"
echo "  Run all tests:"
echo "    npm run test:e2e"
echo ""
echo "  Run specific test file:"
echo "    npm run test:e2e -- tests/e2e/domains.spec.ts"
echo ""
echo "  Run specific test by name:"
echo "    npm run test:e2e -- -g 'create subdomain'"
echo ""
echo "  Debug mode (step through with inspector):"
echo "    npm run test:e2e -- --debug"
echo ""
echo "  Interactive UI (visual test runner):"
echo "    npm run test:e2e -- --ui"
echo ""
echo "  Headed mode (see browser):"
echo "    npm run test:e2e -- --headed"
echo ""
echo "Test Files:"
echo "  1. domains.spec.ts"
echo "     - Create, set primary, delete domains"
echo "     - Duplicate detection"
echo "     - Primary domain protection"
echo "     - RBAC tests"
echo ""
echo "  2. custom-domains.spec.ts"
echo "     - Request custom domain"
echo "     - Display DNS instructions"
echo "     - Verify with polling"
echo "     - Provisioning logs"
echo ""
echo "  3. domain-management.spec.ts"
echo "     - Full domain lifecycle (combined)"
echo "     - All error cases"
echo "     - Authorization checks"
echo ""
echo "  4. packages-coupons.spec.ts"
echo "     - Select package"
echo "     - Validate coupon"
echo "     - Upgrade package"
echo "     - Current plan display"
echo ""
echo "Documentation:"
echo "  - Flow details: frontend/README_COMPLETE.md"
echo "  - Hardening summary: frontend/HARDENING_SUMMARY.md"
echo "  - Auth helpers: frontend/tests/helpers/auth.ts"
echo ""
echo "Test Users (default):"
echo "  TENANT_ADMIN: tenant-admin@test.example.com / Test123!@#"
echo "  TENANT_STAFF: tenant-staff@test.example.com / Test123!@#"
echo "  PLATFORM_SUPERADMIN: platform-admin@test.example.com / Test123!@#"
echo ""
