import type { UserRole } from '../contexts/AuthContext';

export type NavVisibility = 'show' | 'hide';

export interface NavItem {
  id: string;
  label: string;
  to: string;
  featureId?: string;
  allowedRoles?: UserRole[];
  visibility?: NavVisibility;
}

function allowRoles(...roles: UserRole[]): UserRole[] {
  return roles;
}

/**
 * Single source of truth for sidebar navigation.
 *
 * Rules:
 * - `to` MUST match a real route in `src/router.tsx`.
 * - If `featureId` is provided, item is shown only when enabled for the tenant
 *   (based on `/tenant/dashboard` feature tree) OR when feature list is unavailable.
 * - If `allowedRoles` is provided, item is shown only for those roles.
 */
export const NAV_ITEMS: NavItem[] = [
  { id: 'dashboard', label: 'Dashboard', to: '/app/dashboard' },
  { id: 'users', label: 'Users', to: '/app/users' },
  {
    id: 'roles',
    label: 'Roles',
    to: '/app/manage-roles',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
  },
  { id: 'profile', label: 'Profile', to: '/app/profile' },
  { id: 'company', label: 'Company', to: '/app/company' },

  // CMS
  {
    id: 'cms-builder',
    label: 'CMS Builder',
    to: '/app/cms/page-builder',
    featureId: 'cms',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
  },
  {
    id: 'cms-analytics',
    label: 'CMS Analytics',
    to: '/app/cms/analytics',
    featureId: 'cms-analytics',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
  },
  {
    id: 'cms-seo-audit',
    label: 'SEO Audit',
    to: '/app/cms/seo-audit',
    featureId: 'cms-seo-audit',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
  },

  // Tenant core
  {
    id: 'billing',
    label: 'Billing',
    to: '/app/billing',
    featureId: 'billing-dashboard',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
  },
  {
    id: 'feature-billing',
    label: 'Billing (Feature Mapping)',
    to: '/app/billing',
    featureId: 'billing',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'invoices',
    label: 'Invoices',
    to: '/app/billing/invoices',
    featureId: 'billing-invoices-explorer',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
  },
  {
    id: 'domains',
    label: 'Domains',
    to: '/app/domains',
    featureId: 'tenant-domains',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
  },
  {
    id: 'feature-domains',
    label: 'Domains (Feature Mapping)',
    to: '/app/domains',
    featureId: 'domains',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'domain-health',
    label: 'Domain Health',
    to: '/app/domains/health',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
  },
  {
    id: 'packages',
    label: 'Packages',
    to: '/app/packages',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
  },

  // CRM
  { id: 'crm-contacts', label: 'CRM Contacts', to: '/app/crm/contacts' },
  { id: 'crm-companies', label: 'CRM Companies', to: '/app/crm/companies' },
  { id: 'crm-deals', label: 'CRM Deals', to: '/app/crm/deals' },
  { id: 'crm-kanban', label: 'CRM Kanban', to: '/app/crm/kanban' },
  { id: 'crm-tasks', label: 'My CRM Tasks', to: '/app/crm/tasks' },
  { id: 'crm-analytics', label: 'CRM Analytics', to: '/app/crm/analytics' },
  {
    id: 'feature-crm',
    label: 'CRM (Feature Mapping)',
    to: '/app/crm/contacts',
    featureId: 'crm',
    visibility: 'hide',
  },
  {
    id: 'feature-crm-dashboard',
    label: 'CRM Dashboard (Feature Mapping)',
    to: '/app/crm/analytics',
    featureId: 'crm-dashboard',
    visibility: 'hide',
  },
  {
    id: 'feature-crm-sales-funnel',
    label: 'CRM Sales Funnel (Feature Mapping)',
    to: '/app/crm/deals',
    featureId: 'crm-sales-funnel',
    visibility: 'hide',
  },
  {
    id: 'feature-crm-activity-productivity',
    label: 'CRM Activity Productivity (Feature Mapping)',
    to: '/app/crm/analytics',
    featureId: 'crm-activity-productivity',
    visibility: 'hide',
  },

  // Social
  { id: 'social-feed', label: 'Activity Feed', to: '/app/social/feed' },
  { id: 'social-connections', label: 'My Connections', to: '/app/social/connections' },
  { id: 'social-requests', label: 'Connection Requests', to: '/app/social/requests' },

  // Ops
  {
    id: 'notifications',
    label: 'Notification Center',
    to: '/app/notifications',
    featureId: 'notification-center',
  },
  { id: 'chat', label: 'Team Chat', to: '/app/chat' },
  { id: 'support', label: 'Support Tickets', to: '/app/support/tickets' },
  {
    id: 'feature-chat',
    label: 'Chat (Feature Mapping)',
    to: '/app/chat',
    featureId: 'chat',
    visibility: 'hide',
  },
  {
    id: 'feature-support',
    label: 'Support Center (Feature Mapping)',
    to: '/app/support/tickets',
    featureId: 'customer-support-center',
    visibility: 'hide',
  },
  {
    id: 'feature-notifications',
    label: 'Notifications (Feature Mapping)',
    to: '/app/notifications',
    featureId: 'notifications',
    visibility: 'hide',
  },
  {
    id: 'feature-notification-rules-engine',
    label: 'Notification Rules Engine (Feature Mapping)',
    to: '/app/notifications',
    featureId: 'notification-rules-engine',
    visibility: 'hide',
  },

  // Modules
  {
    id: 'accounting',
    label: 'Accounting',
    to: '/app/accounting',
    featureId: 'accounting-dashboard',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
  },
  {
    id: 'feature-accounting',
    label: 'Accounting (Feature Mapping)',
    to: '/app/accounting',
    featureId: 'accounting',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-accounting-aging-report',
    label: 'Accounting Aging Report (Feature Mapping)',
    to: '/app/accounting',
    featureId: 'accounting-aging-report',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-accounting-profit-and-loss',
    label: 'Accounting Profit and Loss (Feature Mapping)',
    to: '/app/accounting',
    featureId: 'accounting-profit-and-loss',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'hrm',
    label: 'HRM',
    to: '/app/hrm',
    featureId: 'hrm-dashboard',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
  },
  {
    id: 'feature-hrm',
    label: 'HRM (Feature Mapping)',
    to: '/app/hrm',
    featureId: 'hrm',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-hrm-attrition-retention',
    label: 'HRM Attrition & Retention (Feature Mapping)',
    to: '/app/hrm',
    featureId: 'hrm-attrition-and-retention',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-hrm-payroll-analytics',
    label: 'HRM Payroll Analytics (Feature Mapping)',
    to: '/app/hrm',
    featureId: 'hrm-payroll-analytics',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'pos',
    label: 'POS & Warehouse',
    to: '/app/pos',
    featureId: 'pos-dashboard',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
  },
  {
    id: 'feature-pos',
    label: 'POS (Feature Mapping)',
    to: '/app/pos',
    featureId: 'pos',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-pos-customer-ltv',
    label: 'POS Customer LTV (Feature Mapping)',
    to: '/app/pos',
    featureId: 'pos-customer-ltv',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-pos-store-comparison',
    label: 'POS Store Comparison (Feature Mapping)',
    to: '/app/pos',
    featureId: 'pos-store-comparison',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'projects',
    label: 'Projects',
    to: '/app/projects',
    featureId: 'projects-dashboard',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
  },
  {
    id: 'feature-projects',
    label: 'Projects (Feature Mapping)',
    to: '/app/projects',
    featureId: 'projects',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-projects-profitability',
    label: 'Projects Profitability (Feature Mapping)',
    to: '/app/projects',
    featureId: 'projects-profitability',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-projects-utilization',
    label: 'Projects Utilization (Feature Mapping)',
    to: '/app/projects',
    featureId: 'projects-utilization',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'vcards',
    label: 'vCards',
    to: '/app/vcards',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
  },

  // Platform admin
  {
    id: 'admin-overview',
    label: 'Platform Overview',
    to: '/app/admin/overview',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
    featureId: 'saas-overview-dashboard',
  },
  {
    id: 'admin-tenants',
    label: 'Tenants & Brands',
    to: '/app/admin/tenants',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
  },
  {
    id: 'admin-support',
    label: 'Support Tickets (Admin)',
    to: '/app/admin/support/tickets',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
  },
  {
    id: 'admin-payment-activity',
    label: 'Payment Activity',
    to: '/app/admin/payments/logs',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
  },
  {
    id: 'admin-invoices',
    label: 'Billing Records',
    to: '/app/admin/invoices',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
  },
  {
    id: 'admin-domains',
    label: 'Domains (Admin)',
    to: '/app/admin/domains',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
  },
  {
    id: 'admin-billing-analytics',
    label: 'Billing Analytics',
    to: '/app/admin/analytics/billing',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
  },
  {
    id: 'admin-system-health',
    label: 'System Health',
    to: '/app/dashboard/system-health',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
    featureId: 'system-health',
  },
  {
    id: 'admin-audit-logs',
    label: 'Audit Logs',
    to: '/app/dashboard/audit-logs',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
    featureId: 'audit-logs',
  },
  {
    id: 'admin-custom-domains',
    label: 'Custom Domains (Admin)',
    to: '/app/dashboard/custom-domains',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
    featureId: 'custom-domains-admin',
  },
  {
    id: 'admin-package-features',
    label: 'Package Features',
    to: '/app/dashboard/package-features',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    featureId: 'package-features',
  },
  {
    id: 'admin-nav-map',
    label: 'Navigation Map',
    to: '/app/admin/navigation-map',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
  },

  // Developer
  {
    id: 'developer',
    label: 'Developer Portal',
    to: '/app/developer',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
  },
  {
    id: 'marketplace',
    label: 'Marketplace',
    to: '/app/marketplace',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
  },
  {
    id: 'ai-tools',
    label: 'AI Tools',
    to: '/app/ai-tools',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
  },
  {
    id: 'hierarchy',
    label: 'Feature Hierarchy',
    to: '/app/hierarchy',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
  },

  // Hidden routes (not shown in sidebar) but kept here so the admin navigation map
  // can treat them as valid UI entry points.
  {
    id: 'feature-platform-admin',
    label: 'Platform Admin (Feature Mapping)',
    to: '/app/admin/overview',
    featureId: 'platform-admin',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-tenant-core',
    label: 'Tenant Core (Feature Mapping)',
    to: '/app/dashboard',
    featureId: 'tenant-core',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-tenant-overview-dashboard',
    label: 'Tenant Overview (Feature Mapping)',
    to: '/app/dashboard',
    featureId: 'tenant-overview-dashboard',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-tenant-billing-dashboard',
    label: 'Tenant Billing (Feature Mapping)',
    to: '/app/billing',
    featureId: 'tenant-billing-dashboard',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-tenant-domains-dashboard',
    label: 'Tenant Domains Dashboard (Feature Mapping)',
    to: '/app/domains',
    featureId: 'tenant-domains-dashboard',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-tenant-urls-and-brands',
    label: 'Tenant URLs & Brands (Feature Mapping)',
    to: '/app/domains',
    featureId: 'tenant-urls-and-brands',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-tenant-quota-usage',
    label: 'Tenant Quota Usage (Feature Mapping)',
    to: '/app/dashboard/tenant-quota',
    featureId: 'tenant-quota-usage',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-revenue-dashboard',
    label: 'Revenue Dashboard (Feature Mapping)',
    to: '/app/admin/analytics/billing',
    featureId: 'revenue-dashboard',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-billing-gateway-performance',
    label: 'Gateway Performance (Feature Mapping)',
    to: '/app/admin/payments/logs',
    featureId: 'billing-gateway-performance',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-affiliate-dashboard',
    label: 'Affiliate Dashboard (Feature Mapping)',
    to: '/app/affiliate',
    featureId: 'affiliate-dashboard',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-accounting-aging-report',
    label: 'Accounting Aging Report (Feature Mapping)',
    to: '/app/accounting',
    featureId: 'accounting-aging-report',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-accounting-profit-and-loss',
    label: 'Accounting P&L (Feature Mapping)',
    to: '/app/accounting',
    featureId: 'accounting-profit-and-loss',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-crm-dashboard',
    label: 'CRM Dashboard (Feature Mapping)',
    to: '/app/crm/analytics',
    featureId: 'crm-dashboard',
    visibility: 'hide',
  },
  {
    id: 'feature-crm-sales-funnel',
    label: 'CRM Sales Funnel (Feature Mapping)',
    to: '/app/crm/analytics',
    featureId: 'crm-sales-funnel',
    visibility: 'hide',
  },
  {
    id: 'feature-crm-activity-productivity',
    label: 'CRM Activity Productivity (Feature Mapping)',
    to: '/app/crm/analytics',
    featureId: 'crm-activity-productivity',
    visibility: 'hide',
  },
  {
    id: 'feature-hrm-attrition-and-retention',
    label: 'HRM Attrition (Feature Mapping)',
    to: '/app/hrm',
    featureId: 'hrm-attrition-and-retention',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-hrm-payroll-analytics',
    label: 'HRM Payroll Analytics (Feature Mapping)',
    to: '/app/hrm',
    featureId: 'hrm-payroll-analytics',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-pos-customer-ltv',
    label: 'POS Customer LTV (Feature Mapping)',
    to: '/app/pos',
    featureId: 'pos-customer-ltv',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-pos-store-comparison',
    label: 'POS Store Comparison (Feature Mapping)',
    to: '/app/pos',
    featureId: 'pos-store-comparison',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-projects-profitability',
    label: 'Projects Profitability (Feature Mapping)',
    to: '/app/projects',
    featureId: 'projects-profitability',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-projects-utilization',
    label: 'Projects Utilization (Feature Mapping)',
    to: '/app/projects',
    featureId: 'projects-utilization',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-notifications',
    label: 'Notifications (Feature Mapping)',
    to: '/app/notifications',
    featureId: 'notifications',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-notification-rules-engine',
    label: 'Notification Rules (Feature Mapping)',
    to: '/app/notifications',
    featureId: 'notification-rules-engine',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-chat-rooms',
    label: 'Chat Rooms (Feature Mapping)',
    to: '/app/chat',
    featureId: 'chat-rooms',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-chat-mentions',
    label: 'Chat Mentions (Feature Mapping)',
    to: '/app/chat',
    featureId: 'chat-mentions-and-notifications',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-customer-portal',
    label: 'Customer Portal (Feature Mapping)',
    to: '/app/billing',
    featureId: 'customer-portal',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-customer-billing-portal',
    label: 'Customer Billing Portal (Feature Mapping)',
    to: '/app/billing',
    featureId: 'customer-billing-portal',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-customer-orders-history',
    label: 'Customer Orders History (Feature Mapping)',
    to: '/app/pos',
    featureId: 'customer-orders-history',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-webhooks',
    label: 'Webhooks (Feature Mapping)',
    to: '/app/developer',
    featureId: 'webhooks',
    allowedRoles: allowRoles('TENANT_ADMIN', 'TENANT_STAFF', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'route-manage-users',
    label: 'Manage Users (Hidden)',
    to: '/app/manage-users',
    visibility: 'hide',
  },
  {
    id: 'route-affiliate',
    label: 'Affiliate (Hidden)',
    to: '/app/affiliate',
    visibility: 'hide',
  },
  {
    id: 'feature-affiliate-dashboard',
    label: 'Affiliate Dashboard (Feature Mapping)',
    to: '/app/affiliate',
    featureId: 'affiliate-dashboard',
    visibility: 'hide',
  },
  {
    id: 'route-billing-offline',
    label: 'Billing Offline (Hidden)',
    to: '/app/billing/offline',
    visibility: 'hide',
  },
  {
    id: 'route-dashboard-cms-menu',
    label: 'CMS Menu (Hidden)',
    to: '/app/dashboard/cms-menu',
    visibility: 'hide',
  },
  {
    id: 'feature-seo',
    label: 'SEO (Feature Mapping)',
    to: '/app/seo',
    featureId: 'seo',
    visibility: 'hide',
  },
  {
    id: 'feature-revenue-dashboard',
    label: 'Revenue Dashboard (Feature Mapping)',
    to: '/app/billing',
    featureId: 'revenue-dashboard',
    visibility: 'hide',
  },
  {
    id: 'feature-billing-gateway-performance',
    label: 'Billing Gateway Performance (Feature Mapping)',
    to: '/app/billing',
    featureId: 'billing-gateway-performance',
    visibility: 'hide',
  },
  {
    id: 'feature-chat-rooms',
    label: 'Chat Rooms (Feature Mapping)',
    to: '/app/chat',
    featureId: 'chat-rooms',
    visibility: 'hide',
  },
  {
    id: 'feature-chat-mentions',
    label: 'Chat Mentions (Feature Mapping)',
    to: '/app/chat',
    featureId: 'chat-mentions-and-notifications',
    visibility: 'hide',
  },
  {
    id: 'feature-cms',
    label: 'CMS (Feature Mapping)',
    to: '/app/cms/page-builder',
    featureId: 'cms',
    visibility: 'hide',
  },
  {
    id: 'feature-cms-analytics',
    label: 'CMS Analytics (Feature Mapping)',
    to: '/app/cms/analytics',
    featureId: 'cms-analytics',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-cms-seo-audit',
    label: 'CMS SEO Audit (Feature Mapping)',
    to: '/app/cms/seo-audit',
    featureId: 'cms-seo-audit',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-seo',
    label: 'SEO (Feature Mapping)',
    to: '/app/seo',
    featureId: 'seo',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'feature-sitemaps',
    label: 'Sitemaps (Feature Mapping)',
    to: '/app/seo',
    featureId: 'sitemaps',
    allowedRoles: allowRoles('TENANT_ADMIN', 'PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'route-dashboard-tenant-quota',
    label: 'Tenant Quota (Hidden)',
    to: '/app/dashboard/tenant-quota',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'route-admin-themes',
    label: 'Admin Themes (Hidden)',
    to: '/app/admin/themes',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'route-admin-settings-ui',
    label: 'Admin UI Settings (Hidden)',
    to: '/app/admin/settings/ui',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'route-admin-settings-advanced',
    label: 'Admin Advanced Settings (Hidden)',
    to: '/app/admin/settings/advanced',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
  {
    id: 'route-admin-payments-offline',
    label: 'Admin Offline Payments (Hidden)',
    to: '/app/admin/payments/offline',
    allowedRoles: allowRoles('PLATFORM_SUPERADMIN'),
    visibility: 'hide',
  },
];
