export enum Role {
  USER = 'USER',
  ADMIN = 'ADMIN',
  OWNER = 'OWNER',
  PLATFORM_SUPER_ADMIN = 'PLATFORM_SUPER_ADMIN',
  PLATFORM_ADMIN_LEGACY = 'PLATFORM_ADMIN_LEGACY',
  TENANT_ADMIN_LEGACY = 'TENANT_ADMIN_LEGACY',
  STAFF_LEGACY = 'STAFF_LEGACY',
  CUSTOMER_LEGACY = 'CUSTOMER_LEGACY',
}
